DROP TABLE IF EXISTS ROUTESITE;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS GUIDEDTOUR;
DROP TABLE IF EXISTS SITE;
DROP TABLE IF EXISTS ROUTE;
DROP TABLE IF EXISTS GUIDE;
DROP TABLE IF EXISTS USERS;